obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_SAMSUNG_LTE430WQ_F0C) += panel-samsung-lte430wq-f0c.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o

obj-$(CONFIG_CTRL_BLIZZARD) += ctrl-blizzard.o
obj-$(CONFIG_PANEL_N800) += panel-n800.o

obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o
obj-$(CONFIG_PANEL_ZOOM2) += panel-zoom2.o
obj-$(CONFIG_SIL9022) += sil9022.o
obj-$(CONFIG_PANEL_BYD_BM240400) += panel-byd-bm240400.o
obj-$(CONFIG_PANEL_LG_4573) += panel-lg-4573.o
obj-$(CONFIG_PANEL_MT_MTF0280) += panel-mt-mtf0280.o
obj-$(CONFIG_PANEL_BOE_HT101) += panel-boe-ht101wsb.o
obj-$(CONFIG_PANEL_LG_LB070WV6) += panel-lg-lb070wv6.o
obj-$(CONFIG_PANEL_WT_WT035NY) += panel-wt-wt035ny.o

